version: '3.4'

services:
  monero-testnet:
    working_dir: /monero
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        CHECKSUM: ${CHECKSUM}
    ports:
      - 28080:28080 # p2p network
      - 28081:28081 # JSON-RPC server
      - 28082:28082 # ZMQ server
    volumes:
      - ./data:/monero/testnet
    # monero-testnet.exan.tech:28081
    command: ./monerod --testnet --p2p-bind-ip=0.0.0.0 --p2p-bind-port=28080 --rpc-bind-ip=0.0.0.0 --rpc-bind-port=28081 --non-interactive --confirm-external-bind  --data-dir /monero/testnet
    restart: on-failure
