version: '3.4'

services:
  # https://hub.docker.com/r/ethereum/client-go
  ethereum-node-mainnet:
    image: ethereum/client-go:alltools-latest
    ports:
      - 8545:8545 # rpc
      - 8546:8546 # websocket
      - 30303:30303
    volumes:
      - ./data/mainnet:/root
    command: >
      geth --rpc 
           --rpcaddr 0.0.0.0
           --rpcport 8545
           --ws
           --wsaddr 0.0.0.0
           --wsport 8546
           --password /ethereum/mainnet/pass
    restart: on-failure

  ethereum-node-testnet:
    image: ethereum/client-go:alltools-latest
    ports:
      - 9545:9545
      - 9546:9546
      - 30303:30303
    volumes:
      - ./data/testnet:/root
    command: >
      geth --rpc 
           --rpcaddr 0.0.0.0
           --rpcport 9545
           --ws
           --wsaddr 0.0.0.0
           --wsport 9546
           --password /ethereum/testnet/pass
           --goerli
    restart: on-failure

  ethereum-node-local:
    image: trufflesuite/ganache-cli
    ports:
      - 10548:8545
    command: >
      ganache-cli 
        # create an account with 1 eth in it
        --account="0x2264248e750146323373851aec1f3f700f6d9ed0ebdc934137c9e007a047197f,1000000000000000000"
        --unlock "0x96afb074FBF48A2b12e31D5f1aB2112d7643801B"
    restart: on-failure
