#!/bin/bash

set -ex

DOCKER_NAME=vanities
SERVICE_NAME=monerodock

DOCKER_TAG="$DOCKER_NAME\/$SERVICE_NAME:latest"

# monero version and checksum
VERSION=v0.15.0.5
CHECKSUM=6cae57cdfc89d85c612980c6a71a0483bbfc1b0f56bbb30e87e933e7ba6fc7e7

# rysnc options:
INSTALL_URL=prod # ssh ip/port
INSTALL_PATH=/coinmine/stuff/monero # add where you want the node to be rsync'd to


# systemd options:
SERVICE_NAME=monero-node # name of the service in services


function set_environment(){
	sed -e "s/VERSION=.*/VERSION=$VERSION/g" .env > tmp
	mv -- tmp .env
	sed -e "s/CHECKSUM=.*/CHECKSUM=$CHECKSUM/g" .env > tmp
	sed -e "s/DOCKER_TAG=.*/DOCKER_TAG=$DOCKER_TAG/g" .env > tmp
	mv -- tmp .env
}
function set_install(){
    sed -e "s/WorkingDirectory=.*/WorkingDirectory=$(pwd)/g" services/$SERVICE_NAME-$1.service > tmp
	mv -- tmp services/$SERVICE_NAME-$1.service
}

# Command line flags used for 'docker compose build'
DOCKER_COMPOSE_BUILD_OPTS=${DOCKER_COMPOSE_BUILD_OPTS-"--parallel"}


base_files="-f docker-compose.yml"

base="docker-compose $base_files" # base config, used standalone for acceptance
base_systemctl="sudo systemctl"


usage="compose -- A helper script for running common docker-compose commands\

Commands:
    help                  Displays this help menu

    up                    Ups any service(s) by name
    down                  Stops any service(s) by name

    config                Displays the config of the compose file
    logs                  Display the logs of any service(s) by name

    install               Copies the files in services/ then enables and starts the systemd service(s)
    uninstall             Removes the files in services/ then disables and stops the systemd service(s)

    *                     Run docker-compose with base config"

case "$1" in
  help)
    echo "$usage"
    ;;
  up)
    for env in "${@:2}"
    do
      services+="$SERVICE_NAME-$env "
    done
    set_environment
    $base up $services
    ;;
  down)
    for env in "${@:2}"
    do
      services+="$SERVICE_NAME-$env "
    done
    $base down $services
    ;;
  config)
    $base config
    ;;
  logs)
    for env in "${@:2}"
    do
      services+="$SERVICE_NAME-$env "
    done
    $base logs -f $services
    ;;
  release)
	rsync -r . $INSTALL_URL:$INSTALL_PATH -v --progress
    ;;
  install)
	sudo cp services/* /etc/systemd/system
    for env in "${@:2}"
    do
      set_install $env
      $base_systemctl enable $SERVICE_NAME-$env.service
      $base_systemctl start $SERVICE_NAME-$env.service
    done
    ;;
  uninstall)
	rm -rf /etc/systemd/monero-node*
    for env in "${@:2}"
    do
      $base_systemctl disable $SERVICE_NAME-$env.service
      $base_systemctl stop $SERVICE_NAME-$env.service
    done
    ;;
  *)
    $base "$@"
    ;;
esac
