version: '3.4'

services:
  monero-node-mainnet:
    image: ${DOCKER_TAG}
    working_dir: /monero
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        CHECKSUM: ${CHECKSUM}
    ports:
      - 18080:18080 # p2p network
      - 18081:18081 # JSON-RPC server
      - 18082:18082 # ZMQ server
    volumes:
      - ./data:/monero/mainnet
    command: >
      ./monerod --p2p-bind-ip=0.0.0.0
                --p2p-bind-port=18080
                --rpc-bind-ip=0.0.0.0
                --rpc-bind-port=18081
                --non-interactive
                --confirm-external-bind
                --data-dir /monero/mainnet
    restart: on-failure

  monero-node-testnet:
    working_dir: /monero
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        CHECKSUM: ${CHECKSUM}
    ports:
      - 28080:28080 # p2p network
      - 28081:28081 # JSON-RPC server
      - 28082:28082 # ZMQ server
    volumes:
      - ./data:/monero/testnet
    # monero-testnet.exan.tech:28081
    command: >
      ./monerod --testnet
                --p2p-bind-ip=0.0.0.0
                --p2p-bind-port=28080
                --rpc-bind-ip=0.0.0.0
                --rpc-bind-port=28081
                --non-interactive
                --confirm-external-bind
                --data-dir /monero/testnet
    restart: on-failure

  monero-node-stagenet:
    working_dir: /monero
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        CHECKSUM: ${CHECKSUM}
    ports:
      - 38080:38080 # p2p network
      - 38081:38081 # JSON-RPC server
      - 38082:38082 # ZMQ server
    volumes:
      - ./data:/monero/stagenet
    # ./monerod --config-file=/monero/stagenet/monerod.conf
    command: ./monerod --stagenet 
                       --p2p-bind-ip 0.0.0.0
                       --p2p-bind-port=38080
                       --rpc-bind-ip=0.0.0.0
                       --rpc-bind-port=38081
                       --non-interactive
                       --confirm-external-bind
                       --data-dir /monero/stagenet
    restart: on-failure

  monero-node-localnet:
    working_dir: /monero
    build:
      context: .
      dockerfile: Dockerfile.localnet
      args:
        VERSION: ${VERSION}
        CHECKSUM: ${CHECKSUM}
    ports:
      - 48080:48080 # p2p network
      - 48081:48081 # JSON-RPC server
      - 48082:48082 # ZMQ server
    volumes:
      - ./data:/monero/localnet
    # monero-stagenet.exan.tech:38081
    command: ./monerod --stagenet
                       --no-igd
                       --hide-my-port
                       --data-dir
                       ~/localnet/node_01
                       --p2p-bind-ip 0.0.0.0
                       --p2p-bind-port=48080
                       --rpc-bind-ip=0.0.0.0
                       --rpc-bind-port=48081 --log-level 0
                       --fixed-difficulty 1
                       --non-interactive
                       --data-dir /monero/localnet
    restart: on-failure
